# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Form.ui'
#
# Created: Wed Sep  5 20:28:40 2012
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_prijaveForm(object):
    def setupUi(self, prijaveForm):
        prijaveForm.setObjectName(_fromUtf8("prijaveForm"))
        prijaveForm.setEnabled(True)
        prijaveForm.resize(1227, 789)
        self.prijaveWidget = QtGui.QWidget(prijaveForm)
        self.prijaveWidget.setObjectName(_fromUtf8("prijaveWidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.prijaveWidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.PrijaveGB = QtGui.QGroupBox(self.prijaveWidget)
        self.PrijaveGB.setObjectName(_fromUtf8("PrijaveGB"))
        self.gridLayout_8 = QtGui.QGridLayout(self.PrijaveGB)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.delavnicaLabel = QtGui.QLabel(self.PrijaveGB)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.delavnicaLabel.setFont(font)
        self.delavnicaLabel.setObjectName(_fromUtf8("delavnicaLabel"))
        self.gridLayout_8.addWidget(self.delavnicaLabel, 5, 0, 1, 1)
        self.prijaveGridLayout = QtGui.QGridLayout()
        self.prijaveGridLayout.setObjectName(_fromUtf8("prijaveGridLayout"))
        self.delavniceButton = QtGui.QCommandLinkButton(self.PrijaveGB)
        self.delavniceButton.setCheckable(True)
        self.delavniceButton.setChecked(True)
        self.delavniceButton.setObjectName(_fromUtf8("delavniceButton"))
        self.prijaveGridLayout.addWidget(self.delavniceButton, 1, 0, 1, 1)
        self.bazenButon = QtGui.QCommandLinkButton(self.PrijaveGB)
        self.bazenButon.setCheckable(True)
        self.bazenButon.setObjectName(_fromUtf8("bazenButon"))
        self.prijaveGridLayout.addWidget(self.bazenButon, 2, 1, 1, 1)
        self.izletButton = QtGui.QCommandLinkButton(self.PrijaveGB)
        self.izletButton.setCheckable(True)
        self.izletButton.setObjectName(_fromUtf8("izletButton"))
        self.prijaveGridLayout.addWidget(self.izletButton, 2, 0, 1, 1)
        self.extraButton = QtGui.QCommandLinkButton(self.PrijaveGB)
        self.extraButton.setCheckable(True)
        self.extraButton.setObjectName(_fromUtf8("extraButton"))
        self.prijaveGridLayout.addWidget(self.extraButton, 3, 1, 1, 1)
        self.majiceButton = QtGui.QCommandLinkButton(self.PrijaveGB)
        self.majiceButton.setCheckable(True)
        self.majiceButton.setChecked(False)
        self.majiceButton.setObjectName(_fromUtf8("majiceButton"))
        self.prijaveGridLayout.addWidget(self.majiceButton, 3, 0, 1, 1)
        self.skupineButton = QtGui.QCommandLinkButton(self.PrijaveGB)
        self.skupineButton.setCheckable(True)
        self.skupineButton.setChecked(True)
        self.skupineButton.setObjectName(_fromUtf8("skupineButton"))
        self.prijaveGridLayout.addWidget(self.skupineButton, 1, 1, 1, 1)
        self.gridLayout_8.addLayout(self.prijaveGridLayout, 2, 0, 1, 2)
        self.kodaLabel = QtGui.QLabel(self.PrijaveGB)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.kodaLabel.setFont(font)
        self.kodaLabel.setObjectName(_fromUtf8("kodaLabel"))
        self.gridLayout_8.addWidget(self.kodaLabel, 4, 0, 1, 1)
        self.koda = QtGui.QLineEdit(self.PrijaveGB)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.koda.setFont(font)
        self.koda.setInputMask(_fromUtf8(""))
        self.koda.setText(_fromUtf8(""))
        self.koda.setObjectName(_fromUtf8("koda"))
        self.gridLayout_8.addWidget(self.koda, 4, 1, 1, 1)
        self.datupPrijav = QtGui.QDateTimeEdit(self.PrijaveGB)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.datupPrijav.setFont(font)
        self.datupPrijav.setCalendarPopup(True)
        self.datupPrijav.setObjectName(_fromUtf8("datupPrijav"))
        self.gridLayout_8.addWidget(self.datupPrijav, 6, 1, 1, 1)
        self.izborDelavnice = QtGui.QComboBox(self.PrijaveGB)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.izborDelavnice.setFont(font)
        self.izborDelavnice.setModelColumn(0)
        self.izborDelavnice.setObjectName(_fromUtf8("izborDelavnice"))
        self.gridLayout_8.addWidget(self.izborDelavnice, 5, 1, 1, 1)
        self.prijaveDneLabel = QtGui.QLabel(self.PrijaveGB)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.prijaveDneLabel.setFont(font)
        self.prijaveDneLabel.setObjectName(_fromUtf8("prijaveDneLabel"))
        self.gridLayout_8.addWidget(self.prijaveDneLabel, 6, 0, 1, 1)
        self.status = QtGui.QLabel(self.PrijaveGB)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.status.setFont(font)
        self.status.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.status.setAutoFillBackground(True)
        self.status.setFrameShape(QtGui.QFrame.NoFrame)
        self.status.setAlignment(QtCore.Qt.AlignCenter)
        self.status.setObjectName(_fromUtf8("status"))
        self.gridLayout_8.addWidget(self.status, 3, 1, 1, 1)
        self.pReset = QtGui.QPushButton(self.PrijaveGB)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pReset.setFont(font)
        self.pReset.setObjectName(_fromUtf8("pReset"))
        self.gridLayout_8.addWidget(self.pReset, 3, 0, 1, 1)
        self.showGui = QtGui.QPushButton(self.PrijaveGB)
        self.showGui.setObjectName(_fromUtf8("showGui"))
        self.gridLayout_8.addWidget(self.showGui, 9, 0, 1, 2)
        self.prijave = QtGui.QTreeWidget(self.PrijaveGB)
        self.prijave.setMouseTracking(True)
        self.prijave.setAllColumnsShowFocus(True)
        self.prijave.setObjectName(_fromUtf8("prijave"))
        self.prijave.headerItem().setText(0, _fromUtf8("Št."))
        self.prijave.header().setCascadingSectionResizes(False)
        self.prijave.header().setDefaultSectionSize(100)
        self.gridLayout_8.addWidget(self.prijave, 8, 0, 1, 2)
        self.gridLayout_2.addWidget(self.PrijaveGB, 0, 0, 1, 1)
        prijaveForm.setCentralWidget(self.prijaveWidget)
        self.delavniceDock = QtGui.QDockWidget(prijaveForm)
        self.delavniceDock.setObjectName(_fromUtf8("delavniceDock"))
        self.dDockContent = QtGui.QWidget()
        self.dDockContent.setObjectName(_fromUtf8("dDockContent"))
        self.gridLayout_16 = QtGui.QGridLayout(self.dDockContent)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.dInputLayout = QtGui.QFormLayout()
        self.dInputLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.dInputLayout.setContentsMargins(-1, 0, -1, -1)
        self.dInputLayout.setHorizontalSpacing(0)
        self.dInputLayout.setVerticalSpacing(5)
        self.dInputLayout.setObjectName(_fromUtf8("dInputLayout"))
        self.didLabel = QtGui.QLabel(self.dDockContent)
        self.didLabel.setObjectName(_fromUtf8("didLabel"))
        self.dInputLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.didLabel)
        self.did = QtGui.QSpinBox(self.dDockContent)
        self.did.setMaximum(999999999)
        self.did.setObjectName(_fromUtf8("did"))
        self.dInputLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.did)
        self.dImeLabel = QtGui.QLabel(self.dDockContent)
        self.dImeLabel.setObjectName(_fromUtf8("dImeLabel"))
        self.dInputLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.dImeLabel)
        self.dIme = QtGui.QLineEdit(self.dDockContent)
        self.dIme.setMaxLength(100)
        self.dIme.setObjectName(_fromUtf8("dIme"))
        self.dInputLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.dIme)
        self.dmaxPrijav = QtGui.QLabel(self.dDockContent)
        self.dmaxPrijav.setObjectName(_fromUtf8("dmaxPrijav"))
        self.dInputLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.dmaxPrijav)
        self.dMax = QtGui.QSpinBox(self.dDockContent)
        self.dMax.setObjectName(_fromUtf8("dMax"))
        self.dInputLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.dMax)
        self.dStarostOdLabel = QtGui.QLabel(self.dDockContent)
        self.dStarostOdLabel.setObjectName(_fromUtf8("dStarostOdLabel"))
        self.dInputLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.dStarostOdLabel)
        self.delavniceGrid = QtGui.QGridLayout()
        self.delavniceGrid.setObjectName(_fromUtf8("delavniceGrid"))
        self.doLabel = QtGui.QLabel(self.dDockContent)
        self.doLabel.setObjectName(_fromUtf8("doLabel"))
        self.delavniceGrid.addWidget(self.doLabel, 0, 1, 1, 1)
        self.dOd = QtGui.QSpinBox(self.dDockContent)
        self.dOd.setObjectName(_fromUtf8("dOd"))
        self.delavniceGrid.addWidget(self.dOd, 0, 0, 1, 1)
        self.dDo = QtGui.QSpinBox(self.dDockContent)
        self.dDo.setObjectName(_fromUtf8("dDo"))
        self.delavniceGrid.addWidget(self.dDo, 0, 2, 1, 1)
        self.dInputLayout.setLayout(3, QtGui.QFormLayout.FieldRole, self.delavniceGrid)
        self.dProsotrLabel = QtGui.QLabel(self.dDockContent)
        self.dProsotrLabel.setObjectName(_fromUtf8("dProsotrLabel"))
        self.dInputLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.dProsotrLabel)
        self.dProstor = QtGui.QLineEdit(self.dDockContent)
        self.dProstor.setObjectName(_fromUtf8("dProstor"))
        self.dInputLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.dProstor)
        self.dOpombeLabel = QtGui.QLabel(self.dDockContent)
        self.dOpombeLabel.setObjectName(_fromUtf8("dOpombeLabel"))
        self.dInputLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.dOpombeLabel)
        self.doGridLayout = QtGui.QGridLayout()
        self.doGridLayout.setObjectName(_fromUtf8("doGridLayout"))
        self.dOpombe = QtGui.QTextBrowser(self.dDockContent)
        self.dOpombe.setMaximumSize(QtCore.QSize(150, 16777215))
        self.dOpombe.setReadOnly(False)
        self.dOpombe.setObjectName(_fromUtf8("dOpombe"))
        self.doGridLayout.addWidget(self.dOpombe, 0, 0, 1, 1)
        self.dInputLayout.setLayout(5, QtGui.QFormLayout.FieldRole, self.doGridLayout)
        self.dVec = QtGui.QCheckBox(self.dDockContent)
        self.dVec.setChecked(False)
        self.dVec.setObjectName(_fromUtf8("dVec"))
        self.dInputLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.dVec)
        self.delavniceButtons = QtGui.QGridLayout()
        self.delavniceButtons.setObjectName(_fromUtf8("delavniceButtons"))
        self.dBrisi = QtGui.QPushButton(self.dDockContent)
        self.dBrisi.setObjectName(_fromUtf8("dBrisi"))
        self.delavniceButtons.addWidget(self.dBrisi, 0, 0, 1, 1)
        self.dShrani = QtGui.QPushButton(self.dDockContent)
        self.dShrani.setObjectName(_fromUtf8("dShrani"))
        self.delavniceButtons.addWidget(self.dShrani, 0, 1, 1, 1)
        self.dInputLayout.setLayout(6, QtGui.QFormLayout.FieldRole, self.delavniceButtons)
        self.gridLayout_16.addLayout(self.dInputLayout, 0, 2, 2, 2)
        self.delavnice = QtGui.QTreeWidget(self.dDockContent)
        self.delavnice.setMinimumSize(QtCore.QSize(0, 0))
        self.delavnice.setMouseTracking(True)
        self.delavnice.setIndentation(0)
        self.delavnice.setObjectName(_fromUtf8("delavnice"))
        self.gridLayout_16.addWidget(self.delavnice, 0, 1, 1, 1)
        self.delavniceDock.setWidget(self.dDockContent)
        prijaveForm.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.delavniceDock)
        self.podatkiDock = QtGui.QDockWidget(prijaveForm)
        self.podatkiDock.setObjectName(_fromUtf8("podatkiDock"))
        self.pDockContent = QtGui.QWidget()
        self.pDockContent.setObjectName(_fromUtf8("pDockContent"))
        self.gridLayout_19 = QtGui.QGridLayout(self.pDockContent)
        self.gridLayout_19.setObjectName(_fromUtf8("gridLayout_19"))
        self.pButtonLayout = QtGui.QGridLayout()
        self.pButtonLayout.setObjectName(_fromUtf8("pButtonLayout"))
        self.pShrani = QtGui.QPushButton(self.pDockContent)
        self.pShrani.setObjectName(_fromUtf8("pShrani"))
        self.pButtonLayout.addWidget(self.pShrani, 1, 2, 1, 1)
        self.pBrisi = QtGui.QPushButton(self.pDockContent)
        self.pBrisi.setObjectName(_fromUtf8("pBrisi"))
        self.pButtonLayout.addWidget(self.pBrisi, 1, 1, 1, 1)
        self.gridLayout_19.addLayout(self.pButtonLayout, 1, 0, 1, 1)
        self.otroci = QtGui.QTreeWidget(self.pDockContent)
        self.otroci.setMouseTracking(True)
        self.otroci.setIndentation(0)
        self.otroci.setAllColumnsShowFocus(True)
        self.otroci.setObjectName(_fromUtf8("otroci"))
        self.gridLayout_19.addWidget(self.otroci, 2, 0, 1, 1)
        self.pLayout = QtGui.QGridLayout()
        self.pLayout.setObjectName(_fromUtf8("pLayout"))
        self.pStarosSkupinaLayout = QtGui.QFormLayout()
        self.pStarosSkupinaLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.pStarosSkupinaLayout.setObjectName(_fromUtf8("pStarosSkupinaLayout"))
        self.pStarost = QtGui.QSpinBox(self.pDockContent)
        self.pStarost.setObjectName(_fromUtf8("pStarost"))
        self.pStarosSkupinaLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.pStarost)
        self.pSkupinaLAyout = QtGui.QFormLayout()
        self.pSkupinaLAyout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.pSkupinaLAyout.setObjectName(_fromUtf8("pSkupinaLAyout"))
        self.pSkupinaLabel = QtGui.QLabel(self.pDockContent)
        self.pSkupinaLabel.setObjectName(_fromUtf8("pSkupinaLabel"))
        self.pSkupinaLAyout.setWidget(0, QtGui.QFormLayout.LabelRole, self.pSkupinaLabel)
        self.pSkupina = QtGui.QComboBox(self.pDockContent)
        self.pSkupina.setEditable(False)
        self.pSkupina.setObjectName(_fromUtf8("pSkupina"))
        self.pSkupinaLAyout.setWidget(0, QtGui.QFormLayout.FieldRole, self.pSkupina)
        self.pStarosSkupinaLayout.setLayout(0, QtGui.QFormLayout.FieldRole, self.pSkupinaLAyout)
        self.pLayout.addLayout(self.pStarosSkupinaLayout, 2, 2, 1, 1)
        self.pImePriimeklayout = QtGui.QFormLayout()
        self.pImePriimeklayout.setObjectName(_fromUtf8("pImePriimeklayout"))
        self.pIme = QtGui.QLineEdit(self.pDockContent)
        self.pIme.setMaxLength(100)
        self.pIme.setObjectName(_fromUtf8("pIme"))
        self.pImePriimeklayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.pIme)
        self.pPriimekLayout = QtGui.QFormLayout()
        self.pPriimekLayout.setObjectName(_fromUtf8("pPriimekLayout"))
        self.pPriimekLabel = QtGui.QLabel(self.pDockContent)
        self.pPriimekLabel.setObjectName(_fromUtf8("pPriimekLabel"))
        self.pPriimekLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.pPriimekLabel)
        self.pPriimek = QtGui.QLineEdit(self.pDockContent)
        self.pPriimek.setMaxLength(100)
        self.pPriimek.setObjectName(_fromUtf8("pPriimek"))
        self.pPriimekLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.pPriimek)
        self.pImePriimeklayout.setLayout(0, QtGui.QFormLayout.FieldRole, self.pPriimekLayout)
        self.pLayout.addLayout(self.pImePriimeklayout, 1, 2, 1, 1)
        self.pCheckLayout = QtGui.QGridLayout()
        self.pCheckLayout.setObjectName(_fromUtf8("pCheckLayout"))
        self.pPrijavnica = QtGui.QCheckBox(self.pDockContent)
        self.pPrijavnica.setObjectName(_fromUtf8("pPrijavnica"))
        self.pCheckLayout.addWidget(self.pPrijavnica, 1, 1, 1, 1)
        self.pMajica = QtGui.QCheckBox(self.pDockContent)
        self.pMajica.setObjectName(_fromUtf8("pMajica"))
        self.pCheckLayout.addWidget(self.pMajica, 1, 2, 1, 1)
        self.pExtra = QtGui.QCheckBox(self.pDockContent)
        self.pExtra.setObjectName(_fromUtf8("pExtra"))
        self.pCheckLayout.addWidget(self.pExtra, 1, 6, 1, 1)
        self.pBazen = QtGui.QCheckBox(self.pDockContent)
        self.pBazen.setObjectName(_fromUtf8("pBazen"))
        self.pCheckLayout.addWidget(self.pBazen, 1, 4, 1, 1)
        self.pIzlet = QtGui.QCheckBox(self.pDockContent)
        self.pIzlet.setObjectName(_fromUtf8("pIzlet"))
        self.pCheckLayout.addWidget(self.pIzlet, 1, 3, 1, 1)
        self.pLayout.addLayout(self.pCheckLayout, 6, 2, 1, 1)
        self.pKontakt = QtGui.QLineEdit(self.pDockContent)
        self.pKontakt.setMaxLength(100)
        self.pKontakt.setObjectName(_fromUtf8("pKontakt"))
        self.pLayout.addWidget(self.pKontakt, 4, 2, 1, 1)
        self.pOidLabel = QtGui.QLabel(self.pDockContent)
        self.pOidLabel.setObjectName(_fromUtf8("pOidLabel"))
        self.pLayout.addWidget(self.pOidLabel, 0, 0, 1, 1)
        self.pNaslovPostaLayout = QtGui.QFormLayout()
        self.pNaslovPostaLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.pNaslovPostaLayout.setObjectName(_fromUtf8("pNaslovPostaLayout"))
        self.pPosta = QtGui.QLineEdit(self.pDockContent)
        self.pPosta.setMaxLength(100)
        self.pPosta.setObjectName(_fromUtf8("pPosta"))
        self.pNaslovPostaLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.pPosta)
        self.pNaslovLayout = QtGui.QFormLayout()
        self.pNaslovLayout.setObjectName(_fromUtf8("pNaslovLayout"))
        self.pNaslovLabel = QtGui.QLabel(self.pDockContent)
        self.pNaslovLabel.setObjectName(_fromUtf8("pNaslovLabel"))
        self.pNaslovLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.pNaslovLabel)
        self.pNaslov = QtGui.QLineEdit(self.pDockContent)
        self.pNaslov.setMaxLength(100)
        self.pNaslov.setObjectName(_fromUtf8("pNaslov"))
        self.pNaslovLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.pNaslov)
        self.pNaslovPostaLayout.setLayout(0, QtGui.QFormLayout.FieldRole, self.pNaslovLayout)
        self.pLayout.addLayout(self.pNaslovPostaLayout, 3, 2, 1, 1)
        self.pImeLabel = QtGui.QLabel(self.pDockContent)
        self.pImeLabel.setObjectName(_fromUtf8("pImeLabel"))
        self.pLayout.addWidget(self.pImeLabel, 1, 0, 1, 1)
        self.pKontaktLabel = QtGui.QLabel(self.pDockContent)
        self.pKontaktLabel.setObjectName(_fromUtf8("pKontaktLabel"))
        self.pLayout.addWidget(self.pKontaktLabel, 4, 0, 1, 1)
        self.pStarostLabel = QtGui.QLabel(self.pDockContent)
        self.pStarostLabel.setObjectName(_fromUtf8("pStarostLabel"))
        self.pLayout.addWidget(self.pStarostLabel, 2, 0, 1, 1)
        self.pPostaLabel = QtGui.QLabel(self.pDockContent)
        self.pPostaLabel.setObjectName(_fromUtf8("pPostaLabel"))
        self.pLayout.addWidget(self.pPostaLabel, 3, 0, 1, 1)
        self.pPlacano = QtGui.QCheckBox(self.pDockContent)
        self.pPlacano.setObjectName(_fromUtf8("pPlacano"))
        self.pLayout.addWidget(self.pPlacano, 6, 0, 1, 1)
        self.pOpombeLabel = QtGui.QLabel(self.pDockContent)
        self.pOpombeLabel.setObjectName(_fromUtf8("pOpombeLabel"))
        self.pLayout.addWidget(self.pOpombeLabel, 5, 0, 1, 1)
        self.poGridLayout = QtGui.QGridLayout()
        self.poGridLayout.setObjectName(_fromUtf8("poGridLayout"))
        self.pOpombe = QtGui.QTextBrowser(self.pDockContent)
        self.pOpombe.setMaximumSize(QtCore.QSize(16777215, 58))
        self.pOpombe.setReadOnly(False)
        self.pOpombe.setObjectName(_fromUtf8("pOpombe"))
        self.poGridLayout.addWidget(self.pOpombe, 0, 0, 1, 1)
        self.pLayout.addLayout(self.poGridLayout, 5, 2, 1, 1)
        self.oid = QtGui.QSpinBox(self.pDockContent)
        self.oid.setMaximum(999999999)
        self.oid.setObjectName(_fromUtf8("oid"))
        self.pLayout.addWidget(self.oid, 0, 2, 1, 1)
        self.gridLayout_19.addLayout(self.pLayout, 0, 0, 1, 1)
        self.podatkiDock.setWidget(self.pDockContent)
        prijaveForm.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.podatkiDock)
        self.animatorjiDock = QtGui.QDockWidget(prijaveForm)
        self.animatorjiDock.setObjectName(_fromUtf8("animatorjiDock"))
        self.aDockContent = QtGui.QWidget()
        self.aDockContent.setObjectName(_fromUtf8("aDockContent"))
        self.gridLayout_12 = QtGui.QGridLayout(self.aDockContent)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.animatorji = QtGui.QTreeWidget(self.aDockContent)
        self.animatorji.setMouseTracking(True)
        self.animatorji.setIndentation(0)
        self.animatorji.setAllColumnsShowFocus(True)
        self.animatorji.setObjectName(_fromUtf8("animatorji"))
        self.gridLayout_12.addWidget(self.animatorji, 0, 0, 1, 1)
        self.aLayout = QtGui.QFrame(self.aDockContent)
        self.aLayout.setMaximumSize(QtCore.QSize(244, 16777215))
        self.aLayout.setFrameShape(QtGui.QFrame.StyledPanel)
        self.aLayout.setFrameShadow(QtGui.QFrame.Raised)
        self.aLayout.setObjectName(_fromUtf8("aLayout"))
        self.gridLayout_11 = QtGui.QGridLayout(self.aLayout)
        self.gridLayout_11.setMargin(0)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.aFrameLayout = QtGui.QFormLayout()
        self.aFrameLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.aFrameLayout.setObjectName(_fromUtf8("aFrameLayout"))
        self.aidLabel = QtGui.QLabel(self.aLayout)
        self.aidLabel.setObjectName(_fromUtf8("aidLabel"))
        self.aFrameLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.aidLabel)
        self.aImeLabel = QtGui.QLabel(self.aLayout)
        self.aImeLabel.setObjectName(_fromUtf8("aImeLabel"))
        self.aFrameLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.aImeLabel)
        self.aIme = QtGui.QLineEdit(self.aLayout)
        self.aIme.setMaxLength(100)
        self.aIme.setObjectName(_fromUtf8("aIme"))
        self.aFrameLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.aIme)
        self.aPriimekLabel = QtGui.QLabel(self.aLayout)
        self.aPriimekLabel.setObjectName(_fromUtf8("aPriimekLabel"))
        self.aFrameLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.aPriimekLabel)
        self.aPriimek = QtGui.QLineEdit(self.aLayout)
        self.aPriimek.setMaxLength(100)
        self.aPriimek.setObjectName(_fromUtf8("aPriimek"))
        self.aFrameLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.aPriimek)
        self.aSkupinaLabel = QtGui.QLabel(self.aLayout)
        self.aSkupinaLabel.setObjectName(_fromUtf8("aSkupinaLabel"))
        self.aFrameLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.aSkupinaLabel)
        self.aSkupina = QtGui.QComboBox(self.aLayout)
        self.aSkupina.setObjectName(_fromUtf8("aSkupina"))
        self.aFrameLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.aSkupina)
        self.aDelavnicaLabel = QtGui.QLabel(self.aLayout)
        self.aDelavnicaLabel.setObjectName(_fromUtf8("aDelavnicaLabel"))
        self.aFrameLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.aDelavnicaLabel)
        self.aDelavnica = QtGui.QComboBox(self.aLayout)
        self.aDelavnica.setObjectName(_fromUtf8("aDelavnica"))
        self.aFrameLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.aDelavnica)
        self.aOpombeLabel = QtGui.QLabel(self.aLayout)
        self.aOpombeLabel.setObjectName(_fromUtf8("aOpombeLabel"))
        self.aFrameLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.aOpombeLabel)
        self.aoGridLayout = QtGui.QGridLayout()
        self.aoGridLayout.setObjectName(_fromUtf8("aoGridLayout"))
        self.aOpombe = QtGui.QTextBrowser(self.aLayout)
        self.aOpombe.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.aOpombe.setReadOnly(False)
        self.aOpombe.setObjectName(_fromUtf8("aOpombe"))
        self.aoGridLayout.addWidget(self.aOpombe, 0, 0, 1, 1)
        self.aFrameLayout.setLayout(5, QtGui.QFormLayout.FieldRole, self.aoGridLayout)
        self.aid = QtGui.QSpinBox(self.aLayout)
        self.aid.setMaximum(999999999)
        self.aid.setObjectName(_fromUtf8("aid"))
        self.aFrameLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.aid)
        self.gridLayout_11.addLayout(self.aFrameLayout, 0, 0, 1, 1)
        self.buttonLayout = QtGui.QGridLayout()
        self.buttonLayout.setObjectName(_fromUtf8("buttonLayout"))
        self.aBrisi = QtGui.QPushButton(self.aLayout)
        self.aBrisi.setObjectName(_fromUtf8("aBrisi"))
        self.buttonLayout.addWidget(self.aBrisi, 0, 0, 1, 1)
        self.aShrani = QtGui.QPushButton(self.aLayout)
        self.aShrani.setObjectName(_fromUtf8("aShrani"))
        self.buttonLayout.addWidget(self.aShrani, 0, 1, 1, 1)
        self.gridLayout_11.addLayout(self.buttonLayout, 1, 0, 1, 1)
        self.gridLayout_12.addWidget(self.aLayout, 0, 1, 1, 1)
        self.animatorjiDock.setWidget(self.aDockContent)
        prijaveForm.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.animatorjiDock)
        self.nastavitveDock = QtGui.QDockWidget(prijaveForm)
        self.nastavitveDock.setFloating(False)
        self.nastavitveDock.setFeatures(QtGui.QDockWidget.AllDockWidgetFeatures)
        self.nastavitveDock.setObjectName(_fromUtf8("nastavitveDock"))
        self.nDockContents = QtGui.QWidget()
        self.nDockContents.setObjectName(_fromUtf8("nDockContents"))
        self.gridLayout = QtGui.QGridLayout(self.nDockContents)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.progressBar = QtGui.QProgressBar(self.nDockContents)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.gridLayout.addWidget(self.progressBar, 0, 0, 1, 1)
        self.label_31 = QtGui.QLabel(self.nDockContents)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_31.setFont(font)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout.addWidget(self.label_31, 1, 0, 1, 1)
        self.lcdNumber = QtGui.QLCDNumber(self.nDockContents)
        self.lcdNumber.setSmallDecimalPoint(False)
        self.lcdNumber.setObjectName(_fromUtf8("lcdNumber"))
        self.gridLayout.addWidget(self.lcdNumber, 1, 1, 1, 1)
        self.axWidget = QAxContainer.QAxWidget(self.nDockContents)
        self.axWidget.setObjectName(_fromUtf8("axWidget"))
        self.gridLayout.addWidget(self.axWidget, 1, 2, 1, 1)
        self.nastavitveDock.setWidget(self.nDockContents)
        prijaveForm.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.nastavitveDock)
        self.skupineDock = QtGui.QDockWidget(prijaveForm)
        self.skupineDock.setObjectName(_fromUtf8("skupineDock"))
        self.sDockContent = QtGui.QWidget()
        self.sDockContent.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.sDockContent.setObjectName(_fromUtf8("sDockContent"))
        self.gridLayout_10 = QtGui.QGridLayout(self.sDockContent)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.skupine = QtGui.QTreeWidget(self.sDockContent)
        self.skupine.setMouseTracking(True)
        self.skupine.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.skupine.setIndentation(0)
        self.skupine.setAnimated(False)
        self.skupine.setAllColumnsShowFocus(False)
        self.skupine.setObjectName(_fromUtf8("skupine"))
        self.gridLayout_10.addWidget(self.skupine, 0, 0, 1, 1)
        self.sFrame = QtGui.QFrame(self.sDockContent)
        self.sFrame.setMinimumSize(QtCore.QSize(212, 0))
        self.sFrame.setMaximumSize(QtCore.QSize(241, 16777215))
        self.sFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.sFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.sFrame.setLineWidth(0)
        self.sFrame.setObjectName(_fromUtf8("sFrame"))
        self.gridLayout_9 = QtGui.QGridLayout(self.sFrame)
        self.gridLayout_9.setMargin(0)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.sLayout = QtGui.QFormLayout()
        self.sLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.sLayout.setObjectName(_fromUtf8("sLayout"))
        self.sidLabel = QtGui.QLabel(self.sFrame)
        self.sidLabel.setObjectName(_fromUtf8("sidLabel"))
        self.sLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.sidLabel)
        self.sImeLabel = QtGui.QLabel(self.sFrame)
        self.sImeLabel.setObjectName(_fromUtf8("sImeLabel"))
        self.sLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.sImeLabel)
        self.skIme = QtGui.QLineEdit(self.sFrame)
        self.skIme.setMaxLength(100)
        self.skIme.setObjectName(_fromUtf8("skIme"))
        self.sLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.skIme)
        self.sProstorLabel = QtGui.QLabel(self.sFrame)
        self.sProstorLabel.setObjectName(_fromUtf8("sProstorLabel"))
        self.sLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.sProstorLabel)
        self.skProstor = QtGui.QLineEdit(self.sFrame)
        self.skProstor.setMaxLength(32767)
        self.skProstor.setReadOnly(False)
        self.skProstor.setObjectName(_fromUtf8("skProstor"))
        self.sLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.skProstor)
        self.sOpombeLabel = QtGui.QLabel(self.sFrame)
        self.sOpombeLabel.setObjectName(_fromUtf8("sOpombeLabel"))
        self.sLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.sOpombeLabel)
        self.soGridLayout = QtGui.QGridLayout()
        self.soGridLayout.setObjectName(_fromUtf8("soGridLayout"))
        self.sOpombe = QtGui.QTextBrowser(self.sFrame)
        self.sOpombe.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.sOpombe.setReadOnly(False)
        self.sOpombe.setObjectName(_fromUtf8("sOpombe"))
        self.soGridLayout.addWidget(self.sOpombe, 0, 0, 1, 1)
        self.sLayout.setLayout(3, QtGui.QFormLayout.FieldRole, self.soGridLayout)
        self.sid = QtGui.QSpinBox(self.sFrame)
        self.sid.setMaximum(999999999)
        self.sid.setObjectName(_fromUtf8("sid"))
        self.sLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.sid)
        self.gridLayout_9.addLayout(self.sLayout, 0, 0, 1, 1)
        self.sButtonLayout = QtGui.QGridLayout()
        self.sButtonLayout.setObjectName(_fromUtf8("sButtonLayout"))
        self.sBrisi = QtGui.QPushButton(self.sFrame)
        self.sBrisi.setObjectName(_fromUtf8("sBrisi"))
        self.sButtonLayout.addWidget(self.sBrisi, 1, 0, 1, 1)
        self.sShrani = QtGui.QPushButton(self.sFrame)
        self.sShrani.setObjectName(_fromUtf8("sShrani"))
        self.sButtonLayout.addWidget(self.sShrani, 1, 1, 1, 1)
        self.gridLayout_9.addLayout(self.sButtonLayout, 1, 0, 1, 1)
        self.gridLayout_10.addWidget(self.sFrame, 0, 1, 1, 1)
        self.skupineDock.setWidget(self.sDockContent)
        prijaveForm.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.skupineDock)

        self.retranslateUi(prijaveForm)
        QtCore.QMetaObject.connectSlotsByName(prijaveForm)

    def retranslateUi(self, prijaveForm):
        prijaveForm.setWindowTitle(QtGui.QApplication.translate("prijaveForm", "Prijave", None, QtGui.QApplication.UnicodeUTF8))
        self.PrijaveGB.setTitle(QtGui.QApplication.translate("prijaveForm", "PRIJAVE", None, QtGui.QApplication.UnicodeUTF8))
        self.delavnicaLabel.setText(QtGui.QApplication.translate("prijaveForm", "DELAVNICA:", None, QtGui.QApplication.UnicodeUTF8))
        self.delavniceButton.setText(QtGui.QApplication.translate("prijaveForm", "Delavnice", None, QtGui.QApplication.UnicodeUTF8))
        self.bazenButon.setText(QtGui.QApplication.translate("prijaveForm", "Bazen", None, QtGui.QApplication.UnicodeUTF8))
        self.izletButton.setText(QtGui.QApplication.translate("prijaveForm", "Izlet", None, QtGui.QApplication.UnicodeUTF8))
        self.extraButton.setText(QtGui.QApplication.translate("prijaveForm", "Extra", None, QtGui.QApplication.UnicodeUTF8))
        self.majiceButton.setText(QtGui.QApplication.translate("prijaveForm", "Majice", None, QtGui.QApplication.UnicodeUTF8))
        self.skupineButton.setText(QtGui.QApplication.translate("prijaveForm", "Skupine", None, QtGui.QApplication.UnicodeUTF8))
        self.kodaLabel.setText(QtGui.QApplication.translate("prijaveForm", "KODA:", None, QtGui.QApplication.UnicodeUTF8))
        self.prijaveDneLabel.setText(QtGui.QApplication.translate("prijaveForm", "PRIJAVE DNE:", None, QtGui.QApplication.UnicodeUTF8))
        self.status.setText(QtGui.QApplication.translate("prijaveForm", "NALAGAM", None, QtGui.QApplication.UnicodeUTF8))
        self.pReset.setText(QtGui.QApplication.translate("prijaveForm", "RESET", None, QtGui.QApplication.UnicodeUTF8))
        self.showGui.setText(QtGui.QApplication.translate("prijaveForm", "Prikaži vsa okna", None, QtGui.QApplication.UnicodeUTF8))
        self.prijave.headerItem().setText(1, QtGui.QApplication.translate("prijaveForm", "Nov stolpec", None, QtGui.QApplication.UnicodeUTF8))
        self.prijave.headerItem().setText(2, QtGui.QApplication.translate("prijaveForm", "Ime", None, QtGui.QApplication.UnicodeUTF8))
        self.prijave.headerItem().setText(3, QtGui.QApplication.translate("prijaveForm", "Starost", None, QtGui.QApplication.UnicodeUTF8))
        self.prijave.headerItem().setText(4, QtGui.QApplication.translate("prijaveForm", "Tip prjave", None, QtGui.QApplication.UnicodeUTF8))
        self.prijave.headerItem().setText(5, QtGui.QApplication.translate("prijaveForm", "Prijava", None, QtGui.QApplication.UnicodeUTF8))
        self.delavniceDock.setWindowTitle(QtGui.QApplication.translate("prijaveForm", "   Delavnice", None, QtGui.QApplication.UnicodeUTF8))
        self.didLabel.setText(QtGui.QApplication.translate("prijaveForm", "DID:", None, QtGui.QApplication.UnicodeUTF8))
        self.dImeLabel.setText(QtGui.QApplication.translate("prijaveForm", "Ime:", None, QtGui.QApplication.UnicodeUTF8))
        self.dmaxPrijav.setText(QtGui.QApplication.translate("prijaveForm", "Max Prijav:", None, QtGui.QApplication.UnicodeUTF8))
        self.dStarostOdLabel.setText(QtGui.QApplication.translate("prijaveForm", "Starost OD:", None, QtGui.QApplication.UnicodeUTF8))
        self.doLabel.setText(QtGui.QApplication.translate("prijaveForm", "DO:", None, QtGui.QApplication.UnicodeUTF8))
        self.dProsotrLabel.setText(QtGui.QApplication.translate("prijaveForm", "Prostor:", None, QtGui.QApplication.UnicodeUTF8))
        self.dOpombeLabel.setText(QtGui.QApplication.translate("prijaveForm", "Opombe:", None, QtGui.QApplication.UnicodeUTF8))
        self.dVec.setText(QtGui.QApplication.translate("prijaveForm", "Večkrat", None, QtGui.QApplication.UnicodeUTF8))
        self.dBrisi.setText(QtGui.QApplication.translate("prijaveForm", "Briši", None, QtGui.QApplication.UnicodeUTF8))
        self.dShrani.setText(QtGui.QApplication.translate("prijaveForm", "Shrani", None, QtGui.QApplication.UnicodeUTF8))
        self.delavnice.setSortingEnabled(True)
        self.delavnice.headerItem().setText(0, QtGui.QApplication.translate("prijaveForm", "Št.", None, QtGui.QApplication.UnicodeUTF8))
        self.delavnice.headerItem().setText(1, QtGui.QApplication.translate("prijaveForm", "Ime", None, QtGui.QApplication.UnicodeUTF8))
        self.delavnice.headerItem().setText(2, QtGui.QApplication.translate("prijaveForm", "Max prijav", None, QtGui.QApplication.UnicodeUTF8))
        self.delavnice.headerItem().setText(3, QtGui.QApplication.translate("prijaveForm", "Min starost", None, QtGui.QApplication.UnicodeUTF8))
        self.delavnice.headerItem().setText(4, QtGui.QApplication.translate("prijaveForm", "Max starost", None, QtGui.QApplication.UnicodeUTF8))
        self.delavnice.headerItem().setText(5, QtGui.QApplication.translate("prijaveForm", "Prostor", None, QtGui.QApplication.UnicodeUTF8))
        self.delavnice.headerItem().setText(6, QtGui.QApplication.translate("prijaveForm", "Večkrat", None, QtGui.QApplication.UnicodeUTF8))
        self.delavnice.headerItem().setText(7, QtGui.QApplication.translate("prijaveForm", "Stanje", None, QtGui.QApplication.UnicodeUTF8))
        self.podatkiDock.setWindowTitle(QtGui.QApplication.translate("prijaveForm", "   Podatki", None, QtGui.QApplication.UnicodeUTF8))
        self.pShrani.setText(QtGui.QApplication.translate("prijaveForm", "Shrani", None, QtGui.QApplication.UnicodeUTF8))
        self.pBrisi.setText(QtGui.QApplication.translate("prijaveForm", "Briši", None, QtGui.QApplication.UnicodeUTF8))
        self.otroci.setSortingEnabled(True)
        self.otroci.headerItem().setText(0, QtGui.QApplication.translate("prijaveForm", "Št.", None, QtGui.QApplication.UnicodeUTF8))
        self.otroci.headerItem().setText(1, QtGui.QApplication.translate("prijaveForm", "Ime", None, QtGui.QApplication.UnicodeUTF8))
        self.otroci.headerItem().setText(2, QtGui.QApplication.translate("prijaveForm", "Priimek", None, QtGui.QApplication.UnicodeUTF8))
        self.otroci.headerItem().setText(3, QtGui.QApplication.translate("prijaveForm", "Starost", None, QtGui.QApplication.UnicodeUTF8))
        self.pSkupinaLabel.setText(QtGui.QApplication.translate("prijaveForm", "Skupina:", None, QtGui.QApplication.UnicodeUTF8))
        self.pPriimekLabel.setText(QtGui.QApplication.translate("prijaveForm", "Priimek: ", None, QtGui.QApplication.UnicodeUTF8))
        self.pPrijavnica.setText(QtGui.QApplication.translate("prijaveForm", "Prijavnica", None, QtGui.QApplication.UnicodeUTF8))
        self.pMajica.setText(QtGui.QApplication.translate("prijaveForm", "Majica", None, QtGui.QApplication.UnicodeUTF8))
        self.pExtra.setText(QtGui.QApplication.translate("prijaveForm", "Extra", None, QtGui.QApplication.UnicodeUTF8))
        self.pBazen.setText(QtGui.QApplication.translate("prijaveForm", "Bazen", None, QtGui.QApplication.UnicodeUTF8))
        self.pIzlet.setText(QtGui.QApplication.translate("prijaveForm", "Izlet", None, QtGui.QApplication.UnicodeUTF8))
        self.pOidLabel.setText(QtGui.QApplication.translate("prijaveForm", "OID:", None, QtGui.QApplication.UnicodeUTF8))
        self.pNaslovLabel.setText(QtGui.QApplication.translate("prijaveForm", "Naslov: ", None, QtGui.QApplication.UnicodeUTF8))
        self.pImeLabel.setText(QtGui.QApplication.translate("prijaveForm", "Ime:", None, QtGui.QApplication.UnicodeUTF8))
        self.pKontaktLabel.setText(QtGui.QApplication.translate("prijaveForm", "Kontakti:", None, QtGui.QApplication.UnicodeUTF8))
        self.pStarostLabel.setText(QtGui.QApplication.translate("prijaveForm", "Starost:", None, QtGui.QApplication.UnicodeUTF8))
        self.pPostaLabel.setText(QtGui.QApplication.translate("prijaveForm", "Pošta:", None, QtGui.QApplication.UnicodeUTF8))
        self.pPlacano.setText(QtGui.QApplication.translate("prijaveForm", "Plačano", None, QtGui.QApplication.UnicodeUTF8))
        self.pOpombeLabel.setText(QtGui.QApplication.translate("prijaveForm", "Opombe:", None, QtGui.QApplication.UnicodeUTF8))
        self.animatorjiDock.setWindowTitle(QtGui.QApplication.translate("prijaveForm", "   Animatorji", None, QtGui.QApplication.UnicodeUTF8))
        self.animatorji.setSortingEnabled(True)
        self.animatorji.headerItem().setText(0, QtGui.QApplication.translate("prijaveForm", "Št.", None, QtGui.QApplication.UnicodeUTF8))
        self.animatorji.headerItem().setText(1, QtGui.QApplication.translate("prijaveForm", "Ime", None, QtGui.QApplication.UnicodeUTF8))
        self.animatorji.headerItem().setText(2, QtGui.QApplication.translate("prijaveForm", "Priimek", None, QtGui.QApplication.UnicodeUTF8))
        self.animatorji.headerItem().setText(3, QtGui.QApplication.translate("prijaveForm", "Skupina", None, QtGui.QApplication.UnicodeUTF8))
        self.animatorji.headerItem().setText(4, QtGui.QApplication.translate("prijaveForm", "Delavnica", None, QtGui.QApplication.UnicodeUTF8))
        self.aidLabel.setText(QtGui.QApplication.translate("prijaveForm", "AID:", None, QtGui.QApplication.UnicodeUTF8))
        self.aImeLabel.setText(QtGui.QApplication.translate("prijaveForm", "Ime:", None, QtGui.QApplication.UnicodeUTF8))
        self.aPriimekLabel.setText(QtGui.QApplication.translate("prijaveForm", "Priimek:", None, QtGui.QApplication.UnicodeUTF8))
        self.aSkupinaLabel.setText(QtGui.QApplication.translate("prijaveForm", "Skupina:", None, QtGui.QApplication.UnicodeUTF8))
        self.aDelavnicaLabel.setText(QtGui.QApplication.translate("prijaveForm", "Delavnica:", None, QtGui.QApplication.UnicodeUTF8))
        self.aOpombeLabel.setText(QtGui.QApplication.translate("prijaveForm", "Opombe:", None, QtGui.QApplication.UnicodeUTF8))
        self.aBrisi.setText(QtGui.QApplication.translate("prijaveForm", "Briši", None, QtGui.QApplication.UnicodeUTF8))
        self.aShrani.setText(QtGui.QApplication.translate("prijaveForm", "Shrani", None, QtGui.QApplication.UnicodeUTF8))
        self.nastavitveDock.setWindowTitle(QtGui.QApplication.translate("prijaveForm", "   Nastavitve", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("prijaveForm", "Prijavljenih:", None, QtGui.QApplication.UnicodeUTF8))
        self.skupineDock.setWindowTitle(QtGui.QApplication.translate("prijaveForm", "   Skupine", None, QtGui.QApplication.UnicodeUTF8))
        self.skupine.setSortingEnabled(True)
        self.skupine.headerItem().setText(0, QtGui.QApplication.translate("prijaveForm", "Št.", None, QtGui.QApplication.UnicodeUTF8))
        self.skupine.headerItem().setText(1, QtGui.QApplication.translate("prijaveForm", "Ime", None, QtGui.QApplication.UnicodeUTF8))
        self.skupine.headerItem().setText(2, QtGui.QApplication.translate("prijaveForm", "Prostor", None, QtGui.QApplication.UnicodeUTF8))
        self.skupine.headerItem().setText(3, QtGui.QApplication.translate("prijaveForm", "Stanje", None, QtGui.QApplication.UnicodeUTF8))
        self.sidLabel.setText(QtGui.QApplication.translate("prijaveForm", "SID:", None, QtGui.QApplication.UnicodeUTF8))
        self.sImeLabel.setText(QtGui.QApplication.translate("prijaveForm", "Ime:", None, QtGui.QApplication.UnicodeUTF8))
        self.sProstorLabel.setText(QtGui.QApplication.translate("prijaveForm", "Prostor:", None, QtGui.QApplication.UnicodeUTF8))
        self.sOpombeLabel.setText(QtGui.QApplication.translate("prijaveForm", "Opombe:", None, QtGui.QApplication.UnicodeUTF8))
        self.sBrisi.setText(QtGui.QApplication.translate("prijaveForm", "Briši", None, QtGui.QApplication.UnicodeUTF8))
        self.sShrani.setText(QtGui.QApplication.translate("prijaveForm", "Shrani", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4 import QAxContainer

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    prijaveForm = QtGui.QMainWindow()
    ui = Ui_prijaveForm()
    ui.setupUi(prijaveForm)
    prijaveForm.show()
    sys.exit(app.exec_())

